config/routes.rb
Rails.application.routes.draw do
 
  get 'user/new'

  get 'user/create'

  get 'user/show'

  get 'user/edit'

  get 'user/update'

  get 'user/destroy'

  get 'user/index'

  resources :opinions

  resources :estados

  resources :ordens

  devise_for :users
  resources :homes

  resources :ubicacions

  resources :tipo_productos

  resources :tipo_comidas

  resources :productos 

  resources :restaurantes do
    member do
      post 'upvote'
      post 'dislike'
    end
  end

  get '/restaurantes/:id/menu' => 'restaurantes#restmenu', as: 'rest_menu'  
	
  get '/restaurantes/:id/platillo' => 'restaurantes#platillo', as: 'platillo' 
	
  get '/restaurantes/:id/platillo/edit' => 'restaurantes#platillo_edit', as: 'platillo_edit' 

  get '/restaurantes/:id/carrito' => 'restaurantes#carrito', as: 'carrito'

  post '/restaurantes/:id/carrito' => 'restaurantes#carrito', as: 'ordenes'

  post '/restaurantes/:id/agregar' => 'restaurantes#agregar', as: 'agregar'

  get '/restaurantes/:id/solicitud' => 'restaurantes#solicitud', as: 'solicitudes'

  get '/restaurantes/:id/comentarios' => 'restaurantes#comentario', as: 'comentario'

  post '/restaurantes/:id/comentarios' => 'restaurantes#comentario', as: 'comentario_agregar'

  get '/' => 'homes#index', as: 'indice' 

end

app/models/restaurante.rb
class Restaurante < ActiveRecord::Base
  has_many :ordens
  has_many :productos
  belongs_to :tipo_comida
  belongs_to :ubicacion
  belongs_to :user
  has_many :opinions
  has_many :votes, dependent: :destroy
  validates_presence_of :nombre_restaurante, message: "Indique un nombre"
  validates_presence_of :telefono, message: "Indique un telefono para el restaurante"
  validates_presence_of :correo_electronico, message: "Indique un email para el restaurante"
  validates :tipo_comida, presence: true
  validates :ubicacion, presence: true

  
def self.search(search)

 if search 

    where('nombre_restaurante LIKE ?', "%#{search}%")    

  end

end

def paypal_url

  values = {
   :business => 'jmarchena93-facilitator@gmail.com',
   :cmd => '_cart',
   :upload => 1,
   :return => 'http://localhost:3000/restaurantes',
   :involve => id
  }

  productos.each_with_index do |item, index|
    values.merge!({
      "amount_#{index+1}" => item.precio,
      "item_name_#{index+1}" => item.nombre_producto,
      "item_number_#{index+1}" => item.id
    })

   end
   
   "https://www.sandbox.paypal.com/cr/cgi-bin/webscr?"+ values.map {|k,v| "#{k}=#{v}"}.join("&") 
  end
end

app/controllers/restaurantes_controller.rb
class RestaurantesController < ApplicationController
  before_action :set_restaurante, only: [:show, :edit, :update, :destroy, :restmenu, :carrito, :platillo, :platillo_edit, :agregar, :solicitud, :comentario]
  before_action :authenticate_user!, only: [:carrito, :edit, :update, :destroy, :new]
  before_action

  # GET /restaurantes
  # GET /restaurantes.json
 def index
    if(@restaurantes = Restaurante.search(params[:searchbox]) == nil)
       @restaurantes = Restaurante.all
    else
       @restaurantes = Restaurante.search(params[:searchbox])
         respond_to do |format|
         format.html # index.html.erb
       end
    end
  end

  def comentario
    if(params[:comentario] != nil)
	 @restaurante.opinions.create(user_id: current_user.id, comentario: params[:comentario])
    end
  end

  def solicitud
    @ordens = Orden.all 
  end

  def platillo_edit
     @producto = Producto.find(params[:foo_param])
     render 'platillo'
  end

  def upvote
    @restaurante = Restaurante.find(params[:id])
    @restaurante.votes.create(user_id: current_user.id)
    redirect_to(restaurantes_path)
  end

  def dislike
    @restaurante = Restaurante.find(params[:id])
    @restaurante.votes.each do |v|
  	  if v.user_id == current_user.id
	        v.destroy  	
	  end
    end
    redirect_to(restaurantes_path)
  end

  def platillo
     @producto = Producto.new
  end

  def restmenu
  end

  def carrito
    @orden = nil
    for n in Orden.all 
	if((n.user_id == current_user.id) and (n.restaurante_id == @restaurante.id) and (n.estado_id == 1))
		@orden = Orden.find(n.id)
	end
    end
 
    if(@orden == nil)
	@orden = Orden.new(user_id: current_user.id, restaurante_id: @restaurante.id, productos: $products, precio: $precio, estado_id: 1, fecha: Time.zone.now, descripcion: "")
	@orden.save
    end

    if(params[:Producto] != nil)
    	producto = Producto.find(params[:Producto])
    else	
	producto = Producto.new(nombre_producto: "", precio: 0)
    end 

    if(params[:Descripcion] != nil)
	 desc = params[:Descripcion]
    else
	 desc = ""	
    end
    
    @orden.descripcion += desc+" "
    @orden.productos += producto.nombre_producto+" "
    @orden.precio += producto.precio
    @orden.save

  end

  def agregar
	for n in Orden.all 
		if((n.user_id == current_user.id) and (n.restaurante_id == @restaurante.id) and (n.estado_id == 1))
			@orden = Orden.find(n.id)
		end
        end
	if(params[:cancelar]=="1")
		@orden.destroy
		redirect_to(restaurantes_path)
	else
		@orden.estado_id = 2
		@orden.save 
         	ModelMailer.new_record_notification(@orden, current_user).deliver
		ModelMailer.email_to_admin(@orden, @restaurante.user).deliver
		 values = {
		   :business => 'jmarchena93-facilitator@gmail.com',
		   :cmd => '_cart',
		   :upload => 1,
		   :return => 'http://localhost:3000/restaurantes',
		   :involve => @restaurante.id
		  }

		    values.merge!({
		      "amount_1" => @orden.precio,
		      "item_name_1" => @orden.productos,
		      "item_number_1" => @orden.id
		    })
   
 		 redirect_to URI.encode("https://www.sandbox.paypal.com/cr/cgi-bin/webscr?"+ values.map {|k,v| "#{k}=#{v}"}.join("&")) 

	end	
  end

  # GET /restaurantes/1
  # GET /restaurantes/1.json
  def show
  end

  # GET /restaurantes/new
  def new
    @restaurante = Restaurante.new(user_id: current_user.id)
  end

  # GET /restaurantes/1/edit
  def edit
  end

  # POST /restaurantes
  # POST /restaurantes.json
  def create
    @restaurante = Restaurante.new(restaurante_params)

    respond_to do |format|
      if @restaurante.save
        format.html { redirect_to @restaurante, notice: 'Restaurante was successfully created.' }
        format.json { render :show, status: :created, location: @restaurante }
      else
        format.html { render :new }
        format.json { render json: @restaurante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurantes/1
  # PATCH/PUT /restaurantes/1.json
  def update
    respond_to do |format|
      if @restaurante.update(restaurante_params)
        format.html { redirect_to @restaurante, notice: 'Restaurante was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurante }
      else
        format.html { render :edit }
        format.json { render json: @restaurante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurantes/1
  # DELETE /restaurantes/1.json
  def destroy
    @restaurante.destroy
    respond_to do |format|
      format.html { redirect_to restaurantes_url, notice: 'Restaurante was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurante
      @restaurante = Restaurante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurante_params
      params.require(:restaurante).permit(:nombre_restaurante, :telefono, :correo_electronico, :fax, :ubicacion_id, :user_id, :tipo_comida_id, :señas)
    end

end

app/helpers/restaurantes_helper.rb
module RestaurantesHelper
		$products = ""	
		$precio = 0.0	
end

app/views/restaurantes/_form.html.erb
<%= form_for(@restaurante) do |f| %>
  <% if @restaurante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurante.errors.count, "error") %> prohibited this restaurante from being saved:</h2>

      <ul>
      <% @restaurante.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
     Tipo de Comida:
  </p>
  <% a = [] %>
  <% k = 0 %>
  <% for n in TipoComida.all %>
  <% 	b = [] %>
  <% 	b[0] = n.tipo_comida %>
  <%    b[1] = n.id %>
  <%    a[k] = b %>
  <% 	k += 1 %>
  <% end %>
  
  <%= select(:restaurante, :tipo_comida_id, a) %>

  <% c = [] %>
  <% j = 0 %>
  <% for i in Ubicacion.all %>
  <% 	d = [] %>
  <% 	d[0] = i.provincia+" "+i.canton+" "+i.distrito %>
  <%    d[1] = i.id %>
  <%    c[j] = d %>
  <% 	j += 1 %>
  <% end %>

  <p>
     Direccion:
  </p>
  <%= select(:restaurante, :ubicacion_id, c) %>

  <div class="field">
    <%= f.label :nombre_restaurante %><br>
    <%= f.text_field :nombre_restaurante %>
  </div> 
  <div class="field">
    <%= f.label :telefono %><br>
    <%= f.number_field :telefono %>
  </div>
  <div class="field">
    <%= f.label :correo_electronico %><br>
    <%= f.text_field :correo_electronico %>
  </div>
  <div class="field">
    <%= f.label :fax %><br>
    <%= f.number_field :fax %>
  </div>
  <div class="field">
    <%= f.label :señas %><br>
    <%= f.text_field :señas %>
  </div>
  
  <%= f.hidden_field :user_id, :value => current_user.id %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurantes/index.html.erb
<!-- CUENTA DE USUARIO-->
<% if user_signed_in? %>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="nav-collapse">
        <ul class="nav">
 	<li class="divider-vertical"></li>       
        <li><%= link_to 'HungryMaps', indice_path %></li> 
	<li class="divider-vertical"></li>
	<li><%= link_to 'Restaurantes', restaurantes_path %></li>
	<li class="divider-vertical"></li>
  	
	<li class="dropdown pull-right">
         <a href="#" data-toggle="dropdown" class="dropdown-toggle"><%= current_user.email %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %></li>
            <li class="divider"></li>
	    <center>
	    <button class="btn btn-link" data-toggle="modal" data-target="#myModal"></li>
	     Soporte 
	    </button>
	    </center>
          </ul>
        </li>

       </ul>
      </div>
    </div>
  </div>
</div> 
<p class='notice'><% notice%></p>
<p class='alert'><% alert%></p>
<%= yield %>
</body>

<% else%>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="nav-collapse">
        <ul class="nav">
	<li class="divider-vertical"></li>
	<li><%= link_to 'HungryMaps', indice_path %></li> 
	<li class="divider-vertical"></li>
	<li><%= link_to 'Restaurantes', restaurantes_path %></li>
	<li class="divider-vertical"></li>
	<li class="dropdown pull-right">
         <a href="#" data-toggle="dropdown" class="dropdown-toggle">Cuenta <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%=link_to "Inicia Sesión", new_user_session_path %></li>
            <li><%=link_to "Registrarse",  new_user_registration_path %></li>
            <li class="divider"></li>
	    <center>
	    <button class="btn btn-link" data-toggle="modal" data-target="#myModal"></li>
	     Soporte 
	    </button>
	    </center>
          </ul>
        </li>    
        </ul>
      </div>
    </div>
  </div>
</div> 
<p class='notice'><% notice%></p>
<p class='alert'><% alert%></p>

<%= yield %>

</body>

<%end%>

<!--HASTA AQUI CUENTA DE USUARIO-->

<!--SOPORTE-MODAL-->

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Soporte</h4>
      </div>
      <div class="modal-body">
	¿Reporte de infracciones o problemas no solucionados? Contáctenos: <b>hungrymaps@gmail.com</b>
	<%= link_to "Facebook", "https://www.facebook.com/HungryMaps", :target => "_blank" %>
	<%= link_to "Twitter", "https://twitter.com/HungryMaps", :target => "_blank" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

<!--HASTA AQUÍ SOPORTE-MODAL-->

<body style="background-color:#CAF078;">
<center>
<br>
<br>
<h1>Lista de Restaurantes</h1>
<br>
<style type="text/css">
.myTable { background-color:#eee;border-collapse:collapse; }
.myTable th { background-color:#45A91A;color:white;width:50%; }
.myTable td, .myTable th { text-align:center; padding:5px;border:1px solid #000; }
</style>

<table class="myTable" style="width:700px">
  <thead>
    <tr>
      <th>Nombre restaurante</th>
      <th>Telefono</th>
      <th>Direccion</th>
      <th>Likes</th>
      <th>Comentarios</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  
  <%= form_tag(restaurantes_path, :method => :get) do %>

    <%= text_field_tag "searchbox", params[:searchbox] %>

    <%= submit_tag "Buscar", :nombre_restaurante => nil %>

<% end %>
    <% @restaurantes.each do |restaurante| %>
      <tr>
        <td><%= link_to restaurante.nombre_restaurante, restaurante %></td>
        <td><%= restaurante.telefono %></td>
        <td><%= restaurante.ubicacion.provincia+" "+restaurante.ubicacion.canton %></td>
	<td><%= pluralize(restaurante.votes.count, "Like") %>
	<% if user_signed_in? %> 
		<% num = restaurante.votes.where(user_id: current_user.id).count %>
		<% if num == 0 %>
			<%= button_to 'Like', upvote_restaurante_path(restaurante), method: :post %>
		<% else %>
			<%= button_to 'Dislike', dislike_restaurante_path(restaurante), method: :post %>
    		<% end %>
    	<% end %>
	</td> 
	
        <td> <%= button_to 'Comentarios', comentario_path(restaurante) %> <td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>   
	<strong> 
	<% if current_user.tipo == "1"%>
    		<%= link_to 'Nuevo Restaurante', new_restaurante_path %>
	<% end %>
	<br>
	<%= link_to 'Sus Ordenes', ordens_path %> </strong>
<% end %>

</center>

app/views/restaurantes/restmenu.html.erb
<!-- CUENTA DE USUARIO-->
<% if user_signed_in? %>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="nav-collapse">
        <ul class="nav">
 	<li class="divider-vertical"></li>       
        <li><%= link_to 'HungryMaps', indice_path %></li> 
	<li class="divider-vertical"></li>
	<li><%= link_to 'Restaurantes', restaurantes_path %></li>
	<li class="divider-vertical"></li>
  	
	<li class="dropdown pull-right">
         <a href="#" data-toggle="dropdown" class="dropdown-toggle"><%= current_user.email %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %></li>
            <li class="divider"></li>
	    <center>
	    <button class="btn btn-link" data-toggle="modal" data-target="#myModal"></li>
	     Soporte 
	    </button>
	    </center>
          </ul>
        </li>

       </ul>
      </div>
    </div>
  </div>
</div> 
<p class='notice'><% notice%></p>
<p class='alert'><% alert%></p>
<%= yield %>
</body>

<% else%>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="nav-collapse">
        <ul class="nav">
	<li class="divider-vertical"></li>
	<li><%= link_to 'HungryMaps', indice_path %></li> 
	<li class="divider-vertical"></li>
	<li><%= link_to 'Restaurantes', restaurantes_path %></li>
	<li class="divider-vertical"></li>
	<li class="dropdown pull-right">
         <a href="#" data-toggle="dropdown" class="dropdown-toggle">Cuenta <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%=link_to "Inicia Sesión", new_user_session_path %></li>
            <li><%=link_to "Registrarse",  new_user_registration_path %></li>
            <li class="divider"></li>
	    <center>
	    <button class="btn btn-link" data-toggle="modal" data-target="#myModal"></li>
	     Soporte 
	    </button>
	    </center>
          </ul>
        </li>    
        </ul>
      </div>
    </div>
  </div>
</div> 
<p class='notice'><% notice%></p>
<p class='alert'><% alert%></p>

<%= yield %>

</body>

<%end%>

<!--HASTA AQUI CUENTA DE USUARIO-->

<!--SOPORTE-MODAL-->

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Soporte</h4>
      </div>
      <div class="modal-body">
	¿Reporte de infracciones o problemas no solucionados? Contáctenos: <b>hungrymaps@gmail.com</b>
	<%= link_to "Facebook", "https://www.facebook.com/HungryMaps", :target => "_blank" %>
	<%= link_to "Twitter", "https://twitter.com/HungryMaps", :target => "_blank" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

<!--HASTA AQUÍ SOPORTE-MODAL-->

<br>
<center>

<p id="notice"><%= notice %></p>

<h1 style="color:green;">Menú</h1>

<br>
<style type="text/css">
.myTable { background-color:#eee;border-collapse:collapse; }
.myTable th { background-color:#45A91A;color:white;width:50%; }
.myTable td, .myTable th { text-align:center; padding:5px;border:1px solid #000; }
</style>

<table class="myTable" style="width:500px">
  <thead>
    <tr>
      <th>Producto</th>
      <th>Precio</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>

<% @restaurante.productos.joins(:tipo_producto).order('tipo_productos.tipo_producto').each do |m| %>
      <tr>
        <td>  <%= m.nombre_producto %></td>
        <td><%= m.precio %> </td>
	<td><%= m.tipo_producto.tipo_producto %> </td>

	<% if user_signed_in? %> 
		<% if current_user.id == @restaurante.user_id %>
			<td><%= link_to 'Editar', platillo_edit_path(foo_param: m.id) %></td>
			<td><%= link_to 'Eliminar', m, method: :delete, data: { confirm: '¿Está seguro de que desea eliminar este platillo?' } %></td>
		<% end %>
	<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p>
  <strong>
  <% if user_signed_in? %> 
	<% if current_user.id == @restaurante.user_id %>
		<%= link_to 'Agregar Platillo', platillo_path%> <br>
	<% end %>
  <% end %>
  <%= link_to 'Ordenar en este restaurante', carrito_path%>
  </strong>
</p>

<br>
<br>

<%= link_to 'Volver', @restaurante %> 

app/views/restaurantes/show.html.erb
<!-- CUENTA DE USUARIO-->
<% if user_signed_in? %>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="nav-collapse">
        <ul class="nav">
 	<li class="divider-vertical"></li>       
        <li><%= link_to 'HungryMaps', indice_path %></li> 
	<li class="divider-vertical"></li>
	<li><%= link_to 'Restaurantes', restaurantes_path %></li>
	<li class="divider-vertical"></li>
  	
	<li class="dropdown pull-right">
         <a href="#" data-toggle="dropdown" class="dropdown-toggle"><%= current_user.email %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %></li>
            <li class="divider"></li>
	    <center>
	    <button class="btn btn-link" data-toggle="modal" data-target="#myModal"></li>
	     Soporte 
	    </button>
	    </center>
          </ul>
        </li>

       </ul>
      </div>
    </div>
  </div>
</div> 
<p class='notice'><% notice%></p>
<p class='alert'><% alert%></p>
<%= yield %>
</body>

<% else%>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="nav-collapse">
        <ul class="nav">
	<li class="divider-vertical"></li>
	<li><%= link_to 'HungryMaps', indice_path %></li> 
	<li class="divider-vertical"></li>
	<li><%= link_to 'Restaurantes', restaurantes_path %></li>
	<li class="divider-vertical"></li>
	<li class="dropdown pull-right">
         <a href="#" data-toggle="dropdown" class="dropdown-toggle">Cuenta <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%=link_to "Inicia Sesión", new_user_session_path %></li>
            <li><%=link_to "Registrarse",  new_user_registration_path %></li>
            <li class="divider"></li>
	    <center>
	    <button class="btn btn-link" data-toggle="modal" data-target="#myModal"></li>
	     Soporte 
	    </button>
	    </center>
          </ul>
        </li>    
        </ul>
      </div>
    </div>
  </div>
</div> 
<p class='notice'><% notice%></p>
<p class='alert'><% alert%></p>

<%= yield %>

</body>

<%end%>

<!--HASTA AQUI CUENTA DE USUARIO-->

<!--SOPORTE-MODAL-->

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Soporte</h4>
      </div>
      <div class="modal-body">
	¿Reporte de infracciones o problemas no solucionados? Contáctenos: <b>hungrymaps@gmail.com</b>
	<%= link_to "Facebook", "https://www.facebook.com/HungryMaps", :target => "_blank" %>
	<%= link_to "Twitter", "https://twitter.com/HungryMaps", :target => "_blank" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

<!--HASTA AQUÍ SOPORTE-MODAL-->

<center>
<p id="notice"><%= notice %></p>
<br>

<h1 style="color:green;">Restaurante</h1>

<p>
  <strong>Nombre restaurante:</strong>
  <%= @restaurante.nombre_restaurante %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @restaurante.telefono %>
</p>

<p>
  <strong>Correo electronico:</strong>
  <%= @restaurante.correo_electronico %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @restaurante.fax %>
</p>

<p>
  <strong>Tipo comida:</strong>
  <%= @restaurante.tipo_comida.tipo_comida %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @restaurante.ubicacion.provincia+" "+@restaurante.ubicacion.canton+" "+@restaurante.ubicacion.distrito %>
</p>

<p>
  <strong>Señas:</strong>
  <%= @restaurante.señas %>
</p>

<p>
  <strong><%= link_to 'Ver el Menú', rest_menu_path%></strong>
</p>

<p>
<% if user_signed_in? %>  
  <% if current_user.id == @restaurante.user.id %>
        <strong> Opciones de Administrador </strong> <br>
	<%= link_to 'Solicitudes de Ordenes', solicitudes_path %> <br>
       	<%= link_to 'Editar Restaurante', edit_restaurante_path %> <br>
       	<%= link_to 'Eliminar', @restaurante, method: :delete, data: { confirm: '¿Está seguro de que desea eliminar este restaurante?' } %> 
  <% end %>
<% end %>
</p>

<br>
<br>

<%= link_to 'Volver', restaurantes_path %>

</center>