config/routes.rb
Rails.application.routes.draw do
 
  get 'user/new'

  get 'user/create'

  get 'user/show'

  get 'user/edit'

  get 'user/update'

  get 'user/destroy'

  get 'user/index'

  resources :opinions

  resources :estados

  resources :ordens

  devise_for :users
  resources :homes

  resources :ubicacions

  resources :tipo_productos

  resources :tipo_comidas

  resources :productos 

  resources :restaurantes do
    member do
      post 'upvote'
      post 'dislike'
    end
  end

  get '/restaurantes/:id/menu' => 'restaurantes#restmenu', as: 'rest_menu'  
	
  get '/restaurantes/:id/platillo' => 'restaurantes#platillo', as: 'platillo' 
	
  get '/restaurantes/:id/platillo/edit' => 'restaurantes#platillo_edit', as: 'platillo_edit' 

  get '/restaurantes/:id/carrito' => 'restaurantes#carrito', as: 'carrito'

  post '/restaurantes/:id/carrito' => 'restaurantes#carrito', as: 'ordenes'

  post '/restaurantes/:id/agregar' => 'restaurantes#agregar', as: 'agregar'

  get '/restaurantes/:id/solicitud' => 'restaurantes#solicitud', as: 'solicitudes'

  get '/restaurantes/:id/comentarios' => 'restaurantes#comentario', as: 'comentario'

  post '/restaurantes/:id/comentarios' => 'restaurantes#comentario', as: 'comentario_agregar'

  get '/' => 'homes#index', as: 'indice' 

end

app/models/estado.rb
class Estado < ActiveRecord::Base
	has_many :ordens
end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/opinion.rb
class Opinion < ActiveRecord::Base
belongs_to :restaurante
belongs_to :user
end

app/models/orden.rb
class Orden < ActiveRecord::Base
	belongs_to :restaurante
	belongs_to :user
	belongs_to :estado
end

app/models/producto.rb
class Producto < ActiveRecord::Base
  belongs_to :restaurante
  belongs_to :tipo_producto
  validates_presence_of :nombre_producto, message: "Indique un nombre para el producto"
  validates_presence_of :precio, message: "Indique un precio"
  validates :precio, numericality: true
  validates :tipo_producto, presence: true
end

app/models/restaurante.rb
class Restaurante < ActiveRecord::Base
  has_many :ordens
  has_many :productos
  belongs_to :tipo_comida
  belongs_to :ubicacion
  belongs_to :user
  has_many :opinions
  has_many :votes, dependent: :destroy
  validates_presence_of :nombre_restaurante, message: "Indique un nombre"
  validates_presence_of :telefono, message: "Indique un telefono para el restaurante"
  validates_presence_of :correo_electronico, message: "Indique un email para el restaurante"
  validates :tipo_comida, presence: true
  validates :ubicacion, presence: true

  
def self.search(search)

 if search 

    where('nombre_restaurante LIKE ?', "%#{search}%")    

  end

end

def paypal_url

  values = {
   :business => 'jmarchena93-facilitator@gmail.com',
   :cmd => '_cart',
   :upload => 1,
   :return => 'http://localhost:3000/restaurantes',
   :involve => id
  }

  productos.each_with_index do |item, index|
    values.merge!({
      "amount_#{index+1}" => item.precio,
      "item_name_#{index+1}" => item.nombre_producto,
      "item_number_#{index+1}" => item.id
    })

   end
   
   "https://www.sandbox.paypal.com/cr/cgi-bin/webscr?"+ values.map {|k,v| "#{k}=#{v}"}.join("&") 
  end
end

app/models/tipo_comida.rb
class TipoComida < ActiveRecord::Base
  has_many :restaurantes
  #validates_presence_of :tipo_comida, message: "Indique un tipo Ej: mexicana, tipica..."

  Restaurante.joins('INNER JOIN tipo_comidas ON restaurantes_id = tipo_comidas.restaurantes_id')
  def self.search(search)
   if(TipoComida.exists?(['tipo_comida LIKE ?', "%#{search}%"]))  #1
   	where('tipo_comida LIKE ?', "%#{search}%" )
   end #1
  end
end

app/models/tipo_producto.rb
class TipoProducto < ActiveRecord::Base
   has_many :productos
   validates_presence_of :tipo_producto, message: "Indique un tipo Ej: Bebidas, Postres, Almuerzos..."
end

app/models/ubicacion.rb
class Ubicacion < ActiveRecord::Base
  has_many :restaurantes
  Restaurante.joins('INNER JOIN ubicacions ON restaurantes_id = ubicacions.restaurantes_id')
  
def self.search(search)
   if(Ubicacion.exists?(['provincia LIKE ?', "%#{search}%"]))  #1
   	where('provincia LIKE ?', "%#{search}%" )
   else
     if(Ubicacion.exists?(['canton LIKE ?', "%#{search}%"]))  #2
   	 where('canton LIKE ?', "%#{search}%" ) 
     else
       if(Ubicacion.exists?(['distrito LIKE ?', "%#{search}%"]))#3
         where('distrito LIKE ?', "%#{search}%" )
       end #3
     end #2
   end #1
end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :restaurante
  has_many :ordens
  has_one :vote
  has_many :opinions
end

app/models/vote.rb
class Vote < ActiveRecord::Base
belongs_to :restaurante
belongs_to :user
end

app/controllers/tipo_comidas_controller.rb
class TipoComidasController < ApplicationController
  before_action :set_tipo_comida, only: [:show, :edit, :update, :destroy]

  # GET /tipo_comidas
  # GET /tipo_comidas.json
  def index
    @tipo_comidas = TipoComida.all
  end

  # GET /tipo_comidas/1
  # GET /tipo_comidas/1.json
  def show
  end

  # GET /tipo_comidas/new
  def new
    @tipo_comida = TipoComida.new
  end

  # GET /tipo_comidas/1/edit
  def edit
  end

  # POST /tipo_comidas
  # POST /tipo_comidas.json
  def create
    @tipo_comida = TipoComida.new(tipo_comida_params)

    respond_to do |format|
      if @tipo_comida.save
        format.html { redirect_to @tipo_comida, notice: 'Tipo comida was successfully created.' }
        format.json { render :show, status: :created, location: @tipo_comida }
      else
        format.html { render :new }
        format.json { render json: @tipo_comida.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_comidas/1
  # PATCH/PUT /tipo_comidas/1.json
  def update
    respond_to do |format|
      if @tipo_comida.update(tipo_comida_params)
        format.html { redirect_to @tipo_comida, notice: 'Tipo comida was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipo_comida }
      else
        format.html { render :edit }
        format.json { render json: @tipo_comida.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_comidas/1
  # DELETE /tipo_comidas/1.json
  def destroy
    @tipo_comida.destroy
    respond_to do |format|
      format.html { redirect_to tipo_comidas_url, notice: 'Tipo comida was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_comida
      @tipo_comida = TipoComida.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_comida_params
      params.require(:tipo_comida).permit(:tipo_comida)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/helpers/ordens_helper.rb
module OrdensHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/restaurantes_helper.rb
module RestaurantesHelper
		$products = ""	
		$precio = 0.0	
end

app/helpers/tipo_comidas_helper.rb
module TipoComidasHelper
end

app/helpers/ubicacions_helper.rb
module UbicacionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/tipo_comidas/_form.html.erb
<%= form_for(@tipo_comida) do |f| %>
  <% if @tipo_comida.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tipo_comida.errors.count, "error") %> prohibited this tipo_comida from being saved:</h2>

      <ul>
      <% @tipo_comida.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo_comida %><br>
    <%= f.text_field :tipo_comida %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tipo_comidas/edit.html.erb
<h1>Editing tipo_comida</h1>

<%= render 'form' %>

<%= link_to 'Show', @tipo_comida %> |
<%= link_to 'Back', tipo_comidas_path %>

app/views/tipo_comidas/index.html.erb
<!-- CUENTA DE USUARIO-->
<% if user_signed_in? %>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="nav-collapse">
        <ul class="nav">
 	<li class="divider-vertical"></li>       
        <li><%= link_to 'HungryMaps', indice_path %></li> 
	<li class="divider-vertical"></li>
	<li><%= link_to 'Restaurantes', restaurantes_path %></li>
	<li class="divider-vertical"></li>
  	
	<li class="dropdown pull-right">
         <a href="#" data-toggle="dropdown" class="dropdown-toggle"><%= current_user.email %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %></li>
            <li class="divider"></li>
	    <center>
	    <button class="btn btn-link" data-toggle="modal" data-target="#myModal"></li>
	     Soporte 
	    </button>
	    </center>
          </ul>
        </li>

       </ul>
      </div>
    </div>
  </div>
</div> 
<p class='notice'><% notice%></p>
<p class='alert'><% alert%></p>
<%= yield %>
</body>

<% else%>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="nav-collapse">
        <ul class="nav">
	<li class="divider-vertical"></li>
	<li><%= link_to 'HungryMaps', indice_path %></li> 
	<li class="divider-vertical"></li>
	<li><%= link_to 'Restaurantes', restaurantes_path %></li>
	<li class="divider-vertical"></li>
	<li class="dropdown pull-right">
         <a href="#" data-toggle="dropdown" class="dropdown-toggle">Cuenta <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%=link_to "Inicia Sesión", new_user_session_path %></li>
            <li><%=link_to "Registrarse",  new_user_registration_path %></li>
            <li class="divider"></li>
	    <center>
	    <button class="btn btn-link" data-toggle="modal" data-target="#myModal"></li>
	     Soporte 
	    </button>
	    </center>
          </ul>
        </li>    
        </ul>
      </div>
    </div>
  </div>
</div> 
<p class='notice'><% notice%></p>
<p class='alert'><% alert%></p>

<%= yield %>

</body>

<%end%>

<!--HASTA AQUI CUENTA DE USUARIO-->

<!--SOPORTE-MODAL-->

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Soporte</h4>
      </div>
      <div class="modal-body">
	¿Reporte de infracciones o problemas no solucionados? Contáctenos: <b>hungrymaps@gmail.com</b>
	<%= link_to "Facebook", "https://www.facebook.com/HungryMaps", :target => "_blank" %>
	<%= link_to "Twitter", "https://twitter.com/HungryMaps", :target => "_blank" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

<!--HASTA AQUÍ SOPORTE-MODAL-->

<body style="background-color:#CAF078;">
<center>
<br>
<br>
<h1>Tipo de Comidas</h1>
<br>
<style type="text/css">
.myTable { background-color:#eee;border-collapse:collapse; }
.myTable th { background-color:#45A91A;color:white;width:50%; }
.myTable td, .myTable th { text-align:center; padding:5px;border:1px solid #000; }
</style>

<table class="myTable" style="width:400px">
  <thead>
    <tr>
      <th>Tipo comida</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <%= form_tag(tipo_comidas_path, :method => :get) do %>
    <%= label_tag(:tipo_comida, "Busqueda por tipo de comida") %>
    <%= text_field_tag "searchbox", params[:searchbox] %>
    <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span> Buscar</button>
        <% end %>


    <% @tipo_comidas.each do |tipo_comida| %>
      <tr>
        <td><%= tipo_comida.tipo_comida %></td>
        <td>
	<% tipo_comida.restaurantes.each do |r|%>
	<div><%= link_to r.nombre_restaurante, restaurante_path(id: r.id) %> </div>
	<% end %>
	</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

</center>

app/views/tipo_comidas/new.html.erb
<!-- CUENTA DE USUARIO-->
<% if user_signed_in? %>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="nav-collapse">
        <ul class="nav">
 	<li class="divider-vertical"></li>       
        <li><%= link_to 'HungryMaps', indice_path %></li> 
	<li class="divider-vertical"></li>
	<li><%= link_to 'Restaurantes', restaurantes_path %></li>
	<li class="divider-vertical"></li>
  	
	<li class="dropdown pull-right">
         <a href="#" data-toggle="dropdown" class="dropdown-toggle"><%= current_user.email %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %></li>
            <li class="divider"></li>
	    <center>
	    <button class="btn btn-link" data-toggle="modal" data-target="#myModal"></li>
	     Soporte 
	    </button>
	    </center>
          </ul>
        </li>

       </ul>
      </div>
    </div>
  </div>
</div> 
<p class='notice'><% notice%></p>
<p class='alert'><% alert%></p>
<%= yield %>
</body>

<% else%>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="nav-collapse">
        <ul class="nav">
	<li class="divider-vertical"></li>
	<li><%= link_to 'HungryMaps', indice_path %></li> 
	<li class="divider-vertical"></li>
	<li><%= link_to 'Restaurantes', restaurantes_path %></li>
	<li class="divider-vertical"></li>
	<li class="dropdown pull-right">
         <a href="#" data-toggle="dropdown" class="dropdown-toggle">Cuenta <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%=link_to "Inicia Sesión", new_user_session_path %></li>
            <li><%=link_to "Registrarse",  new_user_registration_path %></li>
            <li class="divider"></li>
	    <center>
	    <button class="btn btn-link" data-toggle="modal" data-target="#myModal"></li>
	     Soporte 
	    </button>
	    </center>
          </ul>
        </li>    
        </ul>
      </div>
    </div>
  </div>
</div> 
<p class='notice'><% notice%></p>
<p class='alert'><% alert%></p>

<%= yield %>

</body>

<%end%>

<!--HASTA AQUI CUENTA DE USUARIO-->

<!--SOPORTE-MODAL-->

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Soporte</h4>
      </div>
      <div class="modal-body">
	¿Reporte de infracciones o problemas no solucionados?<br>
        Contáctenos: <b>hungrymaps@gmail.com</b>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

<!--HASTA AQUÍ SOPORTE-MODAL-->

<center>
<br>
<h1 style="color:green;">Nuevo Tipo de Comida</h1>

<%= render 'form' %>

<%= link_to 'Back', tipo_comidas_path %>
</center>

app/views/tipo_comidas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo comida:</strong>
  <%= @tipo_comida.tipo_comida %>
</p>

<%= link_to 'Edit', edit_tipo_comida_path(@tipo_comida) %> |
<%= link_to 'Back', tipo_comidas_path %>