config/routes.rb
Rails.application.routes.draw do
 
  get 'user/new'

  get 'user/create'

  get 'user/show'

  get 'user/edit'

  get 'user/update'

  get 'user/destroy'

  get 'user/index'

  resources :opinions

  resources :estados

  resources :ordens

  devise_for :users
  resources :homes

  resources :ubicacions

  resources :tipo_productos

  resources :tipo_comidas

  resources :productos 

  resources :restaurantes do
    member do
      post 'upvote'
      post 'dislike'
    end
  end

  get '/restaurantes/:id/menu' => 'restaurantes#restmenu', as: 'rest_menu'  
	
  get '/restaurantes/:id/platillo' => 'restaurantes#platillo', as: 'platillo' 
	
  get '/restaurantes/:id/platillo/edit' => 'restaurantes#platillo_edit', as: 'platillo_edit' 

  get '/restaurantes/:id/carrito' => 'restaurantes#carrito', as: 'carrito'

  post '/restaurantes/:id/carrito' => 'restaurantes#carrito', as: 'ordenes'

  post '/restaurantes/:id/agregar' => 'restaurantes#agregar', as: 'agregar'

  get '/restaurantes/:id/solicitud' => 'restaurantes#solicitud', as: 'solicitudes'

  get '/restaurantes/:id/comentarios' => 'restaurantes#comentario', as: 'comentario'

  post '/restaurantes/:id/comentarios' => 'restaurantes#comentario', as: 'comentario_agregar'

  get '/' => 'homes#index', as: 'indice' 

end

app/models/estado.rb
class Estado < ActiveRecord::Base
	has_many :ordens
end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/opinion.rb
class Opinion < ActiveRecord::Base
belongs_to :restaurante
belongs_to :user
end

app/models/orden.rb
class Orden < ActiveRecord::Base
	belongs_to :restaurante
	belongs_to :user
	belongs_to :estado
end

app/models/producto.rb
class Producto < ActiveRecord::Base
  belongs_to :restaurante
  belongs_to :tipo_producto
  validates_presence_of :nombre_producto, message: "Indique un nombre para el producto"
  validates_presence_of :precio, message: "Indique un precio"
  validates :precio, numericality: true
  validates :tipo_producto, presence: true
end

app/models/restaurante.rb
class Restaurante < ActiveRecord::Base
  has_many :ordens
  has_many :productos
  belongs_to :tipo_comida
  belongs_to :ubicacion
  belongs_to :user
  has_many :opinions
  has_many :votes, dependent: :destroy
  validates_presence_of :nombre_restaurante, message: "Indique un nombre"
  validates_presence_of :telefono, message: "Indique un telefono para el restaurante"
  validates_presence_of :correo_electronico, message: "Indique un email para el restaurante"
  validates :tipo_comida, presence: true
  validates :ubicacion, presence: true

  
def self.search(search)

 if search 

    where('nombre_restaurante LIKE ?', "%#{search}%")    

  end

end

def paypal_url

  values = {
   :business => 'jmarchena93-facilitator@gmail.com',
   :cmd => '_cart',
   :upload => 1,
   :return => 'http://localhost:3000/restaurantes',
   :involve => id
  }

  productos.each_with_index do |item, index|
    values.merge!({
      "amount_#{index+1}" => item.precio,
      "item_name_#{index+1}" => item.nombre_producto,
      "item_number_#{index+1}" => item.id
    })

   end
   
   "https://www.sandbox.paypal.com/cr/cgi-bin/webscr?"+ values.map {|k,v| "#{k}=#{v}"}.join("&") 
  end
end

app/models/tipo_comida.rb
class TipoComida < ActiveRecord::Base
  has_many :restaurantes
  #validates_presence_of :tipo_comida, message: "Indique un tipo Ej: mexicana, tipica..."

  Restaurante.joins('INNER JOIN tipo_comidas ON restaurantes_id = tipo_comidas.restaurantes_id')
  def self.search(search)
   if(TipoComida.exists?(['tipo_comida LIKE ?', "%#{search}%"]))  #1
   	where('tipo_comida LIKE ?', "%#{search}%" )
   end #1
  end
end

app/models/tipo_producto.rb
class TipoProducto < ActiveRecord::Base
   has_many :productos
   validates_presence_of :tipo_producto, message: "Indique un tipo Ej: Bebidas, Postres, Almuerzos..."
end

app/models/ubicacion.rb
class Ubicacion < ActiveRecord::Base
  has_many :restaurantes
  Restaurante.joins('INNER JOIN ubicacions ON restaurantes_id = ubicacions.restaurantes_id')
  
def self.search(search)
   if(Ubicacion.exists?(['provincia LIKE ?', "%#{search}%"]))  #1
   	where('provincia LIKE ?', "%#{search}%" )
   else
     if(Ubicacion.exists?(['canton LIKE ?', "%#{search}%"]))  #2
   	 where('canton LIKE ?', "%#{search}%" ) 
     else
       if(Ubicacion.exists?(['distrito LIKE ?', "%#{search}%"]))#3
         where('distrito LIKE ?', "%#{search}%" )
       end #3
     end #2
   end #1
end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :restaurante
  has_many :ordens
  has_one :vote
  has_many :opinions
end

app/models/vote.rb
class Vote < ActiveRecord::Base
belongs_to :restaurante
belongs_to :user
end

app/controllers/estados_controller.rb
class EstadosController < ApplicationController
  before_action :set_estado, only: [:show, :edit, :update, :destroy]

  # GET /estados
  # GET /estados.json
  def index
    @estados = Estado.all
  end

  # GET /estados/1
  # GET /estados/1.json
  def show
  end

  # GET /estados/new
  def new
    @estado = Estado.new
  end

  # GET /estados/1/edit
  def edit
  end

  # POST /estados
  # POST /estados.json
  def create
    @estado = Estado.new(estado_params)

    respond_to do |format|
      if @estado.save
        format.html { redirect_to @estado, notice: 'Estado was successfully created.' }
        format.json { render :show, status: :created, location: @estado }
      else
        format.html { render :new }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estados/1
  # PATCH/PUT /estados/1.json
  def update
    respond_to do |format|
      if @estado.update(estado_params)
        format.html { redirect_to @estado, notice: 'Estado was successfully updated.' }
        format.json { render :show, status: :ok, location: @estado }
      else
        format.html { render :edit }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estados/1
  # DELETE /estados/1.json
  def destroy
    @estado.destroy
    respond_to do |format|
      format.html { redirect_to estados_url, notice: 'Estado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estado
      @estado = Estado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estado_params
      params.require(:estado).permit(:estado)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/helpers/ordens_helper.rb
module OrdensHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/restaurantes_helper.rb
module RestaurantesHelper
		$products = ""	
		$precio = 0.0	
end

app/helpers/tipo_comidas_helper.rb
module TipoComidasHelper
end

app/helpers/ubicacions_helper.rb
module UbicacionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/estados/_form.html.erb
<%= form_for(@estado) do |f| %>
  <% if @estado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@estado.errors.count, "error") %> prohibited this estado from being saved:</h2>

      <ul>
      <% @estado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :estado %><br>
    <%= f.text_field :estado %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/estados/edit.html.erb
<h1>Editing estado</h1>

<%= render 'form' %>

<%= link_to 'Show', @estado %> |
<%= link_to 'Back', estados_path %>

app/views/estados/index.html.erb
<!-- CUENTA DE USUARIO-->
<% if user_signed_in? %>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="nav-collapse">
        <ul class="nav">
 	<li class="divider-vertical"></li>       
        <li><%= link_to 'HungryMaps', indice_path %></li> 
	<li class="divider-vertical"></li>
	<li><%= link_to 'Restaurantes', restaurantes_path %></li>
	<li class="divider-vertical"></li>
  	
	<li class="dropdown pull-right">
         <a href="#" data-toggle="dropdown" class="dropdown-toggle"><%= current_user.email %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %></li>
            <li class="divider"></li>
	    <center>
	    <button class="btn btn-link" data-toggle="modal" data-target="#myModal"></li>
	     Soporte 
	    </button>
	    </center>
          </ul>
        </li>

       </ul>
      </div>
    </div>
  </div>
</div> 
<p class='notice'><% notice%></p>
<p class='alert'><% alert%></p>
<%= yield %>
</body>

<% else%>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="nav-collapse">
        <ul class="nav">
	<li class="divider-vertical"></li>
	<li><%= link_to 'HungryMaps', indice_path %></li> 
	<li class="divider-vertical"></li>
	<li><%= link_to 'Restaurantes', restaurantes_path %></li>
	<li class="divider-vertical"></li>
	<li class="dropdown pull-right">
         <a href="#" data-toggle="dropdown" class="dropdown-toggle">Cuenta <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%=link_to "Inicia Sesión", new_user_session_path %></li>
            <li><%=link_to "Registrarse",  new_user_registration_path %></li>
            <li class="divider"></li>
	    <center>
	    <button class="btn btn-link" data-toggle="modal" data-target="#myModal"></li>
	     Soporte 
	    </button>
	    </center>
          </ul>
        </li>    
        </ul>
      </div>
    </div>
  </div>
</div> 
<p class='notice'><% notice%></p>
<p class='alert'><% alert%></p>

<%= yield %>

</body>

<%end%>

<!--HASTA AQUI CUENTA DE USUARIO-->

<!--SOPORTE-MODAL-->

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Soporte</h4>
      </div>
      <div class="modal-body">
	¿Reporte de infracciones o problemas no solucionados?<br>
        Contáctenos: <b>hungrymaps@gmail.com</b>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

<!--HASTA AQUÍ SOPORTE-MODAL-->

<body style="background-color:#CAF078;">
<center>
<br>
<br>
<h1>Estado de Orden</h1>
<br>

<table>
  <thead>
    <tr>
      <th>Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estados.each do |estado| %>
      <tr>
        <td><%= estado.estado %></td>
        <td><%= link_to 'Show', estado %></td>
        <td><%= link_to 'Edit', edit_estado_path(estado) %></td>
        <td><%= link_to 'Destroy', estado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Estado', new_estado_path %>

app/views/estados/new.html.erb
<h1>New estado</h1>

<%= render 'form' %>

<%= link_to 'Back', estados_path %>

app/views/estados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Estado:</strong>
  <%= @estado.estado %>
</p>

<%= link_to 'Edit', edit_estado_path(@estado) %> |
<%= link_to 'Back', estados_path %>